# Build to web from the main branch and upload as artifacts.
---
name: "Build - Web"

# Only run when triggered manually
on:
  workflow_dispatch:

jobs:
  build:
    name: Build & Upload
    runs-on: ubuntu-latest
    
    steps:
      # 1 : Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      
      # 2 : Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.4'
          channel: 'stable'

      # 3 : Enable web
      - name: Enable Flutter web 
        run: flutter config --enable-web

      # 4 : Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 5 : Make sure icons are up to date
      - name: Generate icons
        run: flutter pub run flutter_launcher_icons

      # 6 : Extract version from pubspec.yaml
      - name: Extract version from `pubspec.yaml`
        run: |
          version=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')
          echo "VERSION=$version" >> $GITHUB_ENV

      # 7 : Get and store the short commit hash for this build
      - name: Get short commit hash
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # 8 : Write extracted version and commit hash to `lib/entities/app_info.dart`
      - name: Write version & commit
        run: |
          sed -i "s/missing-version/${{ env.VERSION }}/" lib/entities/app_info.dart
          sed -i "s/missing-commit/${{ env.COMMIT_HASH }}/" lib/entities/app_info.dart

      # 9 : Build the app to web
      - name: Build
        run: flutter build web --release

      # 10 : Upload the build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hifumi-web_v${{ env.VERSION }}
          path: |
            build/web